name: CI

on: [commit_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Issue Labeler
        uses: Naturalclar/issue-action@v1.0.0
        with:
      # Github token
          github-token: ${{ secrets.GITHUB_TOKEN }}
      # keywords to look for in the issue
          keywords: 'Test'
      # assignees to be assigned when keyword is found
      # assignees: # optional
      # labels to be set when keyword is found
          labels: 'TestLabel'
